language: node_js
node_js:
  - 15.3.0
cache: yarn

install: 
  - yarn install

script:
  - echo "skipping tests"
  - yarn run build

deploy: 
  provider: firebase
  token: 
    secure: $FIREBASE_TOKEN
  on:
    branch: gio/feature/travis