language: node_js
node_js:
  - 15.3.0
cache: yarn

install: 
  - yarn global add firebase-tools
  - yarn add vue-cli

script:
  - echo "skipping tests"
  - yarn run build
  - echo "deploying"

after_success: 
  - firebase deploy --token $FIREBASE_TOKEN